export const dashboard = <i className="fa-solid fa-house-chimney"></i>
export const trancations = <i className="fa-solid fa-tent-arrow-left-right"></i>
export const categories = <i className="fa-solid fa-layer-group"></i>
export const settings = <i className="fa-solid fa-gear"></i>
export const accounts = <i className="fa-solid fa-receipt"></i>
export const logout = <i className="fa-solid fa-arrow-right-from-bracket"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-business-time"></i>
export const money = <i className="fa-solid fa-money-bill"></i>
export const stocks = <i className="fa-solid fa-arrow-trend-down"></i>
export const card = <i className="fa-solid fa-credit-card"></i>
export const naira = <i className="fa-solid fa-naira-sign"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const calender = <i className="fa-solid fa-calendar"></i>
export const food = <i className="fa-solid fa-bowl-food"></i>
export const book = <i className="fa-solid fa-book"></i>
export const clothing = <i className="fa-solid fa-shirt"></i>
export const comment = <i className="fa-solid fa-comments"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const electricity = <i className="fa-solid fa-bolt"></i>
export const medical = <i className="fa-solid fa-suitcase-medical"></i>